# Website Settings

title = "Parmar Kudeep"
# gitRepo = "https://github.com/kaushalmodi/hugo-doit-theme.git"

defaultTheme = "black"
keywords = ["blog", "kud33p", "kuldeep", "parmar kuldeep", "coldter"]

gitRepo = ""
# DoIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
# DoIt NEW | 0.2.0 date format
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
images = ["/logo.png"]
# DoIt NEW | 0.2.11 enable PWA support
enablePWA = false

[app]
# optional site title override for the app when added to an iOS home screen or Android launcher
title = "Kud33p"
# whether to omit favicon resource links
noFavicon = false
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = ""
# Safari mask icon color
iconColor = "#5bbad5"
# Windows v8-10 tile color
tileColor = "#da532c"


[search]
enable = true
type = "algolia"
contentLength = 4000
placeholder = ""
maxResultLength = 10
snippetLength = 50
highlightTag = "em"
absoluteURL = false
[search.algolia]
index = ""
appID = ""
searchKey = ""

# common
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[header]
# desktop header mode ("fixed", "normal", "auto")
desktopMode = "fixed"
# mobile header mode ("fixed", "normal", "auto")
mobileMode = "auto"
# theme change mode ("switch", "select")
themeChangeMode = "switch"
# Header title config
[header.title]
# logo = ""
# title name
name = "Kud33p"
# you can add extra information before the name (HTML format is supported), such as icons
post = ""
# whether to use typeit animation for title name
typeit = true

# Footer config
[footer]
enable = true
# Custom content (HTML format is supported)
# custom = ''
# whether to show Hugo and theme info
hugo = true
# Hosted on (HTML format is supported)
# # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
# hostedOn = ''
# whether to show copyright info
copyright = true
# whether to show the author
author = true
# site creation time
# since = 2019
# license info (HTML format is supported)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# TypeIt config
[typeit]
# typing speed between each step (measured in milliseconds)
speed = 100
# blinking speed of the cursor (measured in milliseconds)
cursorSpeed = 1000
# character used for the cursor (HTML format is supported)
cursorChar = "|"
# cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
duration = -1

[section]
paginate = 1000
[section.recentlyUpdated]
enable = true
rss = false
days = 30
maxCount = 10

#  List 
[list]
# list 
paginate = 1000

[social]
GitHub = "coldter"
Email = "hi@kuldeep.tech"
Telegram = "coldter"
RSS = true                # RSS

[home]
# DoIt NEW | 0.2.0 amount of RSS pages
rss = 10
# Home page profile
[home.profile]
enable = true
# URL of avatar shown in home page
# Place your avatar file under static or assets directory
# The filepath is relative to the static or assets directory
avatarURL = "/images/profile-gb.png"
# URL the avatar links to
avatarLinkURL = ""
# DoIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
title = "Hey, It's Kudeep Parmar!"
# subtitle shown in home page
subtitle = ""
# whether to use typeit animation for subtitle
typeit = false
# whether to show social links
social = true
# DoIt NEW | 0.2.0 disclaimer (HTML format is supported)
disclaimer = "Keep it simple, stupid.<br>simple != easy"

# Home page posts
[home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 6
# # DoIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
# # default behavior when you don't set "hiddenFromHomePage" in front matter
# defaultHiddenFromHomePage = false
